export const BEER_LIST_REQUEST = 'BEER_LIST_REQUEST';
export const BEER_LIST_SUCCESS = 'BEER_LIST_SUCCESS';
export const BEER_LIST_FAIL = 'BEER_LIST_FAIL';

export const BEER_DETAILS_REQUEST = 'BEER_DETAILS_REQUEST';
export const BEER_DETAILS_SUCCESS = 'BEER_DETAILS_SUCCESS';
export const BEER_DETAILS_FAIL = 'BEER_DETAILS_FAIL';
