export const GIN_LIST_REQUEST = 'GIN_LIST_REQUEST';
export const GIN_LIST_SUCCESS = 'GIN_LIST_SUCCESS';
export const GIN_LIST_FAIL = 'GIN_LIST_FAIL';

export const GIN_DETAILS_REQUEST = 'GIN_DETAILS_REQUEST';
export const GIN_DETAILS_SUCCESS = 'GIN_DETAILS_SUCCESS';
export const GIN_DETAILS_FAIL = 'GIN_DETAILS_FAIL';
